# Exploratory Data Analysis

## Overview

This notebook explores the cleaned Olist E-commerce dataset to answer key business questions through descriptive statistics and visualizations.

The findings from this notebook will be used to build an interactive Power BI dashboard.

# Exploratory Data Analysis

## Overview

This notebook explores the cleaned Olist E-commerce dataset to answer key business questions through descriptive statistics and visualizations.

The findings from this notebook will be used to build an interactive Power BI dashboard.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("ggplot")

In [3]:
sales = pd.read_csv("../data/processed/sales_clean.csv")

sales.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state,purchase_year,purchase_month,purchase_day,delivery_days,total_sales
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2017-10-11,2017-10-12 03:43:48,9350.0,maua,SP,2017,October,Monday,8.0,38.71
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,2018-08-08,2018-08-08 18:37:50,31570.0,belo horizonte,SP,2018,July,Tuesday,13.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,2018-08-18,2018-08-22 19:07:58,14840.0,guariba,SP,2018,August,Wednesday,9.0,179.12

In [4]:
sales.shape

(119143, 45)

In [5]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 45 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  object
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  object
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  object
 27  payment_sequential             119140 non-null  float64
 28  payment_type                   119140 non-null  object
 29  payment_installments           119140 non-null  float64
 30  payment_value                  119140 non-null  float64
 31  review_id                      118146 non-null  object
 32  review_score                   118146 non-null  float64
 33  review_comment_title           13989 non-null   object
 34  review_comment_message         50245 non-null   object
 35  review_creation_date           118146 non-null  object
 36  review_answer_timestamp        118146 non-null  object
 37  seller_zip_code_prefix         118310 non-null  float64
 38  seller_city                    118310 non-null  object
 39  seller_state                   118310 non-null  object
 40  purchase_year                  119143 non-null  int64
 41  purchase_month                 119143 non-null  object
 42  purchase_day                   119143 non-null  object
 43  delivery_days                  115722 non-null  float64
 44  total_sales                    118310 non-null  float64
dtypes: float64(17), int64(2), object(26)
memory usage: 40.9+ MB

In [6]:
total_sales = sales["total_sales"].sum()

total_orders = sales["order_id"].nunique()

total_customers = sales["customer_unique_id"].nunique()

average_order_value = (
    total_sales / total_orders
)

average_delivery = sales["delivery_days"].mean()

In [7]:
summary = pd.DataFrame({

    "Metric":[

        "Total Sales",

        "Total Orders",

        "Total Customers",

        "Average Order Value",

        "Average Delivery Days"

    ],

    "Value":[

        total_sales,

        total_orders,

        total_customers,

        average_order_value,

        average_delivery

    ]

})

summary

                  Metric         Value
0            Total Sales  1.664373e+07
1           Total Orders  9.944100e+04
2        Total Customers  9.609600e+04
3    Average Order Value  1.673729e+02
4  Average Delivery Days  1.202259e+01